### ISSUE TITLE
Instructions to configure LSP for Godot 4 and latest builds from source

### ISSUE THREAD

**Issue by Karthik-Dulam** [habamax/vim-godot#56]
Currently I'm using a version of Godot compiled by me today (June 30th 2022) (v4.0.alpha.custom_build [fd3970f76]).
I have also tried Godot 4.
LSP does not work with coc.

`[coc.nvim] Server languageserver.godot failed to start: Error: Connection error for languag
eserver.godot: connect ECONNREFUSED 127.0.0.1:6008
`
I used the same configuration as recommended as [here for Godot for 3.2.2+](https://github.com/habamax/vim-godot#setting-up-cocnvim-for-godot-322) since I am using coc.

**Comment by Karthik-Dulam** [comment]
Apparently in newer versions the LSP server port is 6005 by default.

**Comment by Karthik-Dulam** [comment]
@cprn 
I need confirmation that this is the case.
Need to be sure that it wasn't me who changed the port and forgot about it.
Are you sure that the default port in Godot 4 is 6005 instead of 6008?

**Comment by cprn** [comment]
@Karthik-Dulam 
Honestly, no, not at all. I think at some point I must have changed it to a different port as well and coincidentally to the exact same value as you did (i.e. 6005) - the default value still seems to be `6008` because this comment is from 3 days ago:
https://github.com/neoclide/coc.nvim/issues/3910#issuecomment-1173259099
